
apiVersion: v1
kind: Service
metadata:
  name: cdn-microservice-service
spec:
  selector:
    app: cdn-microservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
