apiVersion: v1
kind: Pod
metadata:
  name: busybox-traffic-generator
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do wget -q -O- http://product-catalog-service:8000/; sleep 1; done"]

